### ISSUE TITLE
New component for current user balance

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-crypto#182]
One component is required to be displayed on all pages which will display the user's wallet
The API endpoint required is `https://api.realdevsquad.com/wallet`

The API endpoint is authenticated

Reference: https://github.com/Real-Dev-Squad/website-todo-items/issues/22

This is what API returns:
![image](https://user-images.githubusercontent.com/56217868/111116921-bd227600-858c-11eb-8c97-b8122edacbe7.png)

**Comment by rajakvk** [comment]
I can see the feature already implemented in 'develop' branch. @swarajpure 
/routes/wallets.js
/controllers/getOwnWallet.js
models/fetchWallet.js
