### ISSUE TITLE
`Create New Auction` can be made a button instead of clickable h2

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-crypto#216]
![image](https://user-images.githubusercontent.com/56217868/122687112-67680480-d232-11eb-9fe4-471f25d0b1fe.png)

Currently it's a simple h2 tag and there's un-clickable normal text below it
We need to seperate out both of them, so the `Create New Auction` can be made into a typical button

**Comment by shubham-y** [comment]
I'd like to take this up

**Comment by swarajpure** [comment]
> I'd like to take this up

Assigned to you!
