### ISSUE TITLE
Set the minimum send/receive amount to 1.

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-crypto#220]
We have a send/ receive currency feature (WIP) on  https://crypto.realdevsquad.com/.

Currently, there are no limits set on the amount of currency to be sent/received. The user is able to enter negative amount as well.
Refer the images attached below.
 
![image](https://user-images.githubusercontent.com/66248039/123841385-1be9e080-d92d-11eb-92d9-2a7baa4a7ef6.png)

![image](https://user-images.githubusercontent.com/66248039/123841553-53f12380-d92d-11eb-92f2-934c11ee673b.png)

The task is to set minimum amount to `1` both for send and receive feature.

Thank you!

**Comment by iRahulP** [comment]
Hi @Rucha1499 , Can I try working on this issue?
