### ISSUE TITLE
Redirect the user to `https://www.realdevsquad.com/` for logging in

### ISSUE THREAD

**Issue by Rucha1499** [Real-Dev-Squad/website-crypto#223]
The user's money is being displayed on https://crypto.realdevsquad.com/ if the user is logged in.
![image](https://user-images.githubusercontent.com/66248039/124167947-1d98dd00-dac2-11eb-8792-ad9692da7df5.png)

If the user isn't logged in, this text & link is displayed.
![image](https://user-images.githubusercontent.com/66248039/124167217-6b611580-dac1-11eb-84f9-65f567f7c269.png)

When clicked on the link, the below page is displayed.
![image](https://user-images.githubusercontent.com/66248039/124167593-d01c7000-dac1-11eb-8819-8de5fba72700.png)

The above is surely not a good user experience. So, till the time we have some login system integrated into crypto site, we can simply redirect the user to https://www.realdevsquad.com/ for login.

**Comment by anshika29** [comment]
I ll take this up
