### ISSUE TITLE
Standardize Navbar across Real Dev Squad

### ISSUE THREAD

**Issue by rahilkapoor** [Real-Dev-Squad/website-crypto#240]
### Design of New Navbar:
https://www.figma.com/file/bpFHG9hXM13GSLmTkoNsrF/Navbar?node-id=0%3A1

## Few Details 
- font : Roboto
- weight: 700
- active color : #49A82E
- hover color : #49A82E
- font size : 16 px (try making it in rem)
- active underline height : 3px (color : #49A82E)
- RDS Logo Size - 50x50

### Pay Attention
=> Underline should be under the text as shown in the image and not inside the container in which the text persists.
=> Underline should be only under the active tab, it should not be visible on hover
=> Clicking on RDS logo we should be redirected to https://www.realdevsquad.com/
=> The full navbar should be changed to the toggle menu when the screen width is less than 970px.
=> For the stock and auction tabs, we need a small navbar something like we have in status-site.
=> User should be directed to `my.realdevsquad.com` on clicking `User Greet`
![image](https://user-images.githubusercontent.com/78433013/144760822-2c209a68-04e6-4345-a506-e05b7232c19c.png)

### There might be slight changes for different domains and you are free to ask in the comments for that

**Comment by shubham-y** [comment]
I would like to take this issue
