### ISSUE TITLE
Update contributing.md

### ISSUE THREAD

**Issue by akshay1502** [Real-Dev-Squad/website-crypto#250]
Make the [How can you make your pull request](https://github.com/Real-Dev-Squad/website-crypto/blob/develop/CONTRIBUTING.md#how-can-you-make-your-first-pull-request) section similar to this ->
https://github.com/Real-Dev-Squad/website-www/blob/develop/CONTRIBUTE.md
> don't include point no.7

**Comment by rajat-mehra05** [comment]
Can you assign me this ? Would love to take this issue.

**Comment by DeRaowl** [comment]
@akshay1502 Can you assign me this ?
