### ISSUE TITLE
Refactor- Navbar 

### ISSUE THREAD

**Issue by MehulKChaudhari** [Real-Dev-Squad/website-crypto#280]
## What happend
Now in our app Navbar is imported on every page which is not good to do. Upon visiting every page the navbar is rendered again.  

Doing that if in future we add animations those will not be visible and other things. 
![image](https://user-images.githubusercontent.com/55375534/180188376-1385a045-9427-415a-bb67-7c07a8408342.png)

![image](https://user-images.githubusercontent.com/55375534/180188438-2aaa8b89-daf0-4eee-a957-23f58891246c.png)

![image](https://user-images.githubusercontent.com/55375534/180188680-3b64b7ca-afc2-4975-bc49-fb30c92a786a.png)

and so on 

## what is expected 
Navbar should be used only once in the app

**Comment by Maianki** [comment]
Hi, @MehulKChaudhari I would like to take this issue.
