### ISSUE TITLE
Add: tailwind CSS

### ISSUE THREAD

**Issue by MehulKChaudhari** [Real-Dev-Squad/website-crypto#285]
We have to add tailwind CSS to our crypto site repo. 

Links: 
[Tailwind CSS docs](https://tailwindcss.com/docs/installation)

**Comment by manish591** [comment]
Hey, can i take this task?

**Comment by MehulKChaudhari** [comment]
> Hey, can i take this task?

Assigned to you. Please let me know if you need any help. 
Thank you.
