### ISSUE TITLE
Issue with index page

### ISSUE THREAD

**Issue by Kratika0907** [Real-Dev-Squad/website-crypto#30]
1. Coins value are not there
2. Page is not mobile responsive for transaction part.

![image](https://user-images.githubusercontent.com/59445453/93808207-4c4b7280-fc69-11ea-9bb9-56393c011146.png)

**Comment by whyDontI** [comment]
@prakashchoudhary07 Took care of this issue in following PR.

https://github.com/Real-Dev-Squad/website-crypto/pull/34
