### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-crypto#42]
- Add CONTRIBUTING.md to this repo
- Reference can be taken from: https://github.com/Real-Dev-Squad/website-welcome/blob/main/CONTRIBUTING.md
- Modify it accordingly

**Comment by PPInfy** [comment]
Can I take this?

**Comment by swarajpure** [comment]
@PPInfy done! You could join our Discord server which we use for communication: https://discord.gg/gTarzr

**Comment by PPInfy** [comment]
I have completed the required 4 PRs for hacktober. I can contribute to this as well if there is no one else to pick it up. I want to give an opportunity for another noob like me to complete the PRs. Let me know if this is fine with you.

**Comment by swarajpure** [comment]
Sure! Thanks for letting us know!

**Comment by anu-ragi** [comment]
is this issue still open to take?
