### ISSUE TITLE
Nav bar on all pages 

### ISSUE THREAD

**Issue by Kratika0907** [Real-Dev-Squad/website-crypto#78]

**Comment by gauravchauhan2403** [comment]
Please assign this to me.

**Comment by gauravchauhan2403** [comment]
Done changes please close it. It is not relevent anymore @Kratika0907 @swarajpure

**Comment by gauravchauhan2403** [comment]
This seems to be not relevent any more as ankush sir have asked me to add the navbar in global styles so this is not required anymore.

**Comment by swarajpure** [comment]
New issue: https://github.com/Real-Dev-Squad/website-crypto/issues/82
