### ISSUE TITLE
Coin animation and css fix 

### ISSUE THREAD

**Issue by Kratika0907** [Real-Dev-Squad/website-crypto#79]

**Comment by gauravchauhan2403** [comment]
please assign this to me.

**Comment by gauravchauhan2403** [comment]
Please review and merge. Suggest me changes if needed. @Kratika0907 
![Screenshot from 2020-12-08 23-03-36](https://user-images.githubusercontent.com/56407052/101520042-ec33b500-39a9-11eb-8c3c-035dc6ececf9.png)

**Comment by Kratika0907** [comment]
The numbers inside are small as compared to size of coin. I think we can keep the font-size relative wrt to the coin size.  Also there should be more space between coins and those send and receive. Rest looks good to me. Thanks

**Comment by gauravchauhan2403** [comment]
Please review this. @Kratika0907 
![Screenshot from 2020-12-09 00-24-09](https://user-images.githubusercontent.com/56407052/101528175-f4ddb880-39b4-11eb-8abd-131a1a19e197.png)

**Comment by whyDontI** [comment]
Closing this issue, as the PR is merged.
