### ISSUE TITLE
Numbers should be centered in the coins

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-crypto#85]
![image](https://user-images.githubusercontent.com/1935403/102709385-0483b980-425f-11eb-9da9-592b62c275f2.png)

**Comment by chhatrapalsinhzala007** [comment]
hyy i can do this .

**Comment by ankushdharkar** [comment]
Yes @chhatrapalsinhzala007, all yours

**Comment by ankushdharkar** [comment]
Any progress on this @chhatrapalsinhzala007?

**Comment by Kratika0907** [comment]
Not needed now
