### ISSUE TITLE
Button text should be centered

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-crypto#86]
![image](https://user-images.githubusercontent.com/1935403/102709389-15342f80-425f-11eb-89c4-04401a5fcdb7.png)

**Comment by akanksha26281** [comment]
Hey!
I'm new to open-source, and I'd like to start contributing.
This seems like a very good starting point. 
I was not getting any good issues to work on for few days, and would love to contribute on this as my first issue.

**Comment by akanksha26281** [comment]
Hey!
I'm new to open-source, and I'd like to start contributing. This seems like a very good starting point.
I was not getting any good issues to work on for few days, and would love to contribute on this as my first issue.
Can I start working on this issue?

**Comment by ankushdharkar** [comment]
Sorry @akanksha26281. Missed seeing your message earlier. Please join our [Discord server](https://discord.gg/nJv6jB9hFe) where we are more active.

In the meantime, you can work on this issue: #87
