### ISSUE TITLE
Layout fix for big displays

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-crypto#87]
We would like the content to be more closer together and the negative space to exist on the sides

![image](https://user-images.githubusercontent.com/1935403/102709420-52002680-425f-11eb-8066-ec11f347ddeb.png)

**Comment by Kswierk** [comment]
Can I try to fix this one ?

**Comment by ankushdharkar** [comment]
Sure @Kswierk, all yours.

**Comment by Kswierk** [comment]
hey, as I see now it looks like its already fixed:
![display-bug](https://user-images.githubusercontent.com/63197737/102912519-cd3f2380-447d-11eb-9374-f7266cbdfba1.PNG)

**Comment by ankushdharkar** [comment]
@Kswierk We have a Discord server that I'd like to invite you to [join](https://discord.gg/PHu9Z2PwZN). We coordinate a bunch of tasks there and it's a free and open community of developers, most of them new.

Regarding the layout of the design, we would ideally want it to look like this:

![temp](https://user-images.githubusercontent.com/1935403/103037486-cb7a6c00-4520-11eb-8d76-f5997a6368dd.png)

**Comment by akanksha26281** [comment]
Can I work on this issue if it's unsolved?

**Comment by Kswierk** [comment]
Yes please

**Comment by akanksha26281** [comment]
> Yes please

Can you help me find the folder which contains the problem please.

**Comment by swarajpure** [comment]
> 
> 
> > Yes please
> 
> Can you help me find the folder which contains the problem please.

Hello Akanksha!
We at Real Dev Squad communicate over Discord. 
Can you please join it so we can help you out in an efficient way?
Link to join it: https://discord.gg/hT4ynQnE
(Link will be valid for next 24hours)

**Comment by swarajpure** [comment]
@akanksha26281 are you working on this issue?

**Comment by rajakvk** [comment]
@swarajpure, @ankushdharkar, please invite me to discord server. I like to contribute.

**Comment by ankushdharkar** [comment]
@rajakvk Sure: https://discord.gg/8APrAsAp

**Comment by rajakvk** [comment]
@ankushdharkar, Please confirm graph should appear in between "Go to currency Exchange button" and "Latest Transaction" section in desktop screens. 
Since it is my first contribution in this project, shall fork, add my updates in branch "feature/layout-fix-87"?

**Comment by ankushdharkar** [comment]
@rajakvk
Yes, that's correct
Forking it or branching it(if you're added in the org here), both are fine. Thanks!

I see you sent this out in PR #167 :) 👍
