### ISSUE TITLE
Swap location of '+' and '-' buttons in the shop page

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-crypto#98]
<img width="1430" alt="temp" src="https://user-images.githubusercontent.com/1935403/103163692-385a6400-47b6-11eb-8704-72ed7880f2e7.png">

**Comment by JoseLRiano** [comment]
### Hello
Can I help you solve this issue?

**Comment by ankushdharkar** [comment]
All yours @JoseLRiano! Have fun!
